name: Deployment

on:
  workflow_run:
    workflows: ["Integration"]
    types: [completed]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installing pnpm
        run: npm install -g pnpm

      - name: Installing dependencies
        run: pnpm install

      - name: Docker Build
        run: docker build -t demo:${{ github.sha }} .
